package com.basiclab.iot.video.domain;

import com.basiclab.iot.video.support.JsonFields;
import lombok.Data;

import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Data
public class AlgorithmTaskRow {
    private Long id;
    private String taskName;
    private String taskCode;
    private String taskType;
    private String executor;
    private Boolean isEnabled;
    private String runStatus;
    private Boolean alertEventEnabled;
    private Integer alertEventSuppressTime;
    private Float detectConf;
    private String modelNames;
    private String modelIds;
    private Integer runtimeControlPort;
    private String runtimeBinPath;
    private String schedulePolicy;
    private Boolean preferGpu;
    private Integer extractInterval;
    private Integer frameSkip;
    private String serviceServerIp;
    private Integer servicePort;
    private Integer serviceProcessId;
    private Instant serviceLastHeartbeat;
    private String serviceLogPath;
    private List<String> deviceIds;
    private List<String> deviceNames;
    private String rtmpInputUrl;
    private String rtmpOutputUrl;
    private Boolean trackingEnabled;
    private Float trackingSimilarityThreshold;
    private Integer trackingMaxAge;
    private Float trackingSmoothAlpha;
    private String alertClassNames;
    private Boolean faceDetectionEnabled;
    private Boolean plateDetectionEnabled;
    private Boolean faceMatchingEnabled;
    private String faceLibraryIds;
    private Float faceMatchingThreshold;
    private Boolean plateMatchingEnabled;
    private String plateLibraryIds;
    private String matchingBusinessTags;
    private Boolean alertNotificationEnabled;
    private String alertNotificationConfig;
    private Integer alarmSuppressTime;
    private Instant lastNotifyTime;
    private Integer spaceId;
    private String spaceName;
    private String cronExpression;
    private String patrolMode;
    private Integer patrolIntervalSec;
    private Integer patrolPoolSize;
    private String focusDeviceId;
    private Integer status;
    private String exceptionReason;
    private Integer totalFrames;
    private Integer totalDetections;
    private Integer totalCaptures;
    private Instant lastProcessTime;
    private Instant lastSuccessTime;
    private Instant lastCaptureTime;
    private String defenseMode;
    private String defenseSchedule;
    private Long targetNodeId;
    private Long nodeId;
    private Boolean samSupplementEnabled;
    private String samSupplementConfig;
    private Boolean motionGateEnabled;
    private String motionGateConfig;
    private Boolean poseAnalysisEnabled;
    private String poseAnalysisConfig;
    private Boolean poseIntentEnabled;
    private String poseLibraryIds;
    private Float poseIntentThreshold;
    private String poseIntentConfig;
    private Boolean postProcessEnabled;
    private String postProcessScript;
    private Integer postProcessReplicas;
    private Instant createdAt;
    private Instant updatedAt;

    public Map<String, Object> toMap() {
        Map<String, Object> m = new HashMap<>();
        m.put("id", id);
        m.put("task_name", taskName);
        m.put("task_code", taskCode);
        m.put("task_type", taskType);
        m.put("device_ids", deviceIds != null ? deviceIds : new ArrayList<>());
        m.put("device_names", deviceNames != null ? deviceNames : new ArrayList<>());
        m.put("model_ids", JsonFields.parseJsonList(modelIds));
        m.put("model_names", modelNames);
        m.put("detect_conf", detectConf != null ? detectConf : 0.5f);
        m.put("extract_interval", extractInterval);
        m.put("rtmp_input_url", rtmpInputUrl);
        m.put("rtmp_output_url", rtmpOutputUrl);
        m.put("tracking_enabled", Boolean.TRUE.equals(trackingEnabled));
        m.put("tracking_similarity_threshold", trackingSimilarityThreshold != null ? trackingSimilarityThreshold : 0.2f);
        m.put("tracking_max_age", trackingMaxAge != null ? trackingMaxAge : 25);
        m.put("tracking_smooth_alpha", trackingSmoothAlpha != null ? trackingSmoothAlpha : 0.25f);
        m.put("alert_event_enabled", Boolean.TRUE.equals(alertEventEnabled));
        m.put("alert_event_suppress_time", alertEventSuppressTime != null ? alertEventSuppressTime : 5);
        m.put("alert_class_names", JsonFields.parseJsonList(alertClassNames));
        m.put("face_detection_enabled", faceDetectionEnabled == null || faceDetectionEnabled);
        m.put("plate_detection_enabled", plateDetectionEnabled == null || plateDetectionEnabled);
        m.put("face_matching_enabled", Boolean.TRUE.equals(faceMatchingEnabled));
        m.put("face_library_ids", JsonFields.parseJsonList(faceLibraryIds));
        m.put("face_library_names", new ArrayList<>());
        m.put("face_matching_threshold", faceMatchingThreshold);
        m.put("plate_matching_enabled", Boolean.TRUE.equals(plateMatchingEnabled));
        m.put("plate_library_ids", JsonFields.parseJsonList(plateLibraryIds));
        m.put("plate_library_names", new ArrayList<>());
        m.put("matching_business_tags", JsonFields.parseJsonList(matchingBusinessTags));
        m.put("alert_notification_enabled", Boolean.TRUE.equals(alertNotificationEnabled));
        m.put("alert_notification_config", JsonFields.parseJsonObject(alertNotificationConfig));
        m.put("alarm_suppress_time", alarmSuppressTime != null ? alarmSuppressTime : 300);
        m.put("last_notify_time", formatInstant(lastNotifyTime));
        m.put("space_id", spaceId);
        m.put("space_name", spaceName);
        m.put("cron_expression", cronExpression);
        m.put("frame_skip", frameSkip != null ? frameSkip : 25);
        m.put("patrol_mode", patrolMode != null ? patrolMode : "pool");
        m.put("patrol_interval_sec", patrolIntervalSec != null ? patrolIntervalSec : 10);
        m.put("patrol_pool_size", patrolPoolSize != null ? patrolPoolSize : 4);
        m.put("focus_device_id", focusDeviceId);
        m.put("status", status != null ? status : 0);
        m.put("is_enabled", Boolean.TRUE.equals(isEnabled));
        m.put("exception_reason", exceptionReason);
        m.put("total_frames", totalFrames != null ? totalFrames : 0);
        m.put("total_detections", totalDetections != null ? totalDetections : 0);
        m.put("total_captures", totalCaptures != null ? totalCaptures : 0);
        m.put("last_process_time", formatInstant(lastProcessTime));
        m.put("last_success_time", formatInstant(lastSuccessTime));
        m.put("last_capture_time", formatInstant(lastCaptureTime));
        m.put("defense_mode", defenseMode != null ? defenseMode : "full");
        m.put("defense_schedule", defenseSchedule);
        m.put("schedule_policy", schedulePolicy != null ? schedulePolicy : "local");
        m.put("prefer_gpu", preferGpu != null ? preferGpu : true);
        m.put("target_node_id", targetNodeId);
        m.put("node_id", nodeId);
        m.put("executor", executor != null ? executor : "cpp");
        m.put("runtime_bin_path", runtimeBinPath);
        m.put("runtime_control_port", runtimeControlPort);
        m.put("service_server_ip", serviceServerIp);
        m.put("service_port", servicePort);
        m.put("service_process_id", serviceProcessId);
        m.put("service_last_heartbeat", formatInstant(serviceLastHeartbeat));
        m.put("service_log_path", serviceLogPath);
        m.put("algorithm_services", new ArrayList<>());
        m.put("sam_supplement_enabled", Boolean.TRUE.equals(samSupplementEnabled));
        m.put("sam_supplement_config", JsonFields.parseJsonObject(samSupplementConfig));
        m.put("motion_gate_enabled", Boolean.TRUE.equals(motionGateEnabled));
        m.put("motion_gate_config", JsonFields.parseJsonObject(motionGateConfig));
        m.put("pose_analysis_enabled", Boolean.TRUE.equals(poseAnalysisEnabled));
        m.put("pose_analysis_config", JsonFields.parseJsonObject(poseAnalysisConfig));
        m.put("pose_intent_enabled", Boolean.TRUE.equals(poseIntentEnabled));
        m.put("pose_library_ids", JsonFields.parseJsonList(poseLibraryIds));
        m.put("pose_library_names", new ArrayList<>());
        m.put("pose_intent_threshold", poseIntentThreshold);
        m.put("pose_intent_config", JsonFields.parseJsonObject(poseIntentConfig));
        m.put("post_process_enabled", Boolean.TRUE.equals(postProcessEnabled));
        m.put("post_process_script", postProcessScript);
        m.put("post_process_replicas", postProcessReplicas != null ? postProcessReplicas : 1);
        m.put("created_at", formatInstant(createdAt));
        m.put("updated_at", formatInstant(updatedAt));
        return m;
    }

    private static String formatInstant(Instant instant) {
        return instant != null ? instant.toString() : null;
    }
}
