package com.basiclab.iot.video.service;

import com.basiclab.iot.video.config.VideoProperties;
import com.basiclab.iot.video.dal.AlgorithmTaskRepository;
import com.basiclab.iot.video.domain.AlgorithmTaskRow;
import com.basiclab.iot.video.exception.VideoBusinessException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class RuntimeIniGenerator {

    private final AlgorithmTaskRepository taskRepository;
    private final VideoProperties videoProperties;

    public String generate(AlgorithmTaskRow task, Path logPath) throws IOException {
        if (task.getDeviceIds() == null || task.getDeviceIds().isEmpty()) {
            throw new VideoBusinessException(400, "任务 " + task.getId() + " 未绑定设备，无法生成 RUNTIME 配置");
        }
        String deviceId = task.getDeviceIds().get(0);
        Map<String, String> device = taskRepository.findDevice(deviceId)
                .orElseThrow(() -> new VideoBusinessException(400, "设备不存在: " + deviceId));
        String rtspUrl = device.get("source");
        if (rtspUrl == null || rtspUrl.isBlank()) {
            throw new VideoBusinessException(400, "设备 " + deviceId + " 无可用 RTSP/source 地址");
        }
        String taskType = normalizeTaskType(task.getTaskType());
        int controlPort = task.getRuntimeControlPort() != null
                ? task.getRuntimeControlPort()
                : 8000 + (int) (task.getId() % 1000);
        Path configDir = Path.of(videoProperties.getRuntime().getConfigDir());
        Files.createDirectories(configDir);
        Path iniPath = configDir.resolve("task_" + task.getId() + ".ini");
        Path logDir = logPath.getParent() != null ? logPath.getParent() : logPath;
        Path alertImageDir = logDir.resolve("alerts");
        Files.createDirectories(alertImageDir);

        String modelPath = resolveModelPath();
        String classesPath = resolveClassesPath();
        String hookUrl = videoProperties.getRuntime().getHookBaseUrl() + "/video/alert/hook";
        String heartbeatUrl = videoProperties.getRuntime().getHeartbeatBaseUrl()
                + "/video/algorithm/heartbeat/" + ("patrol".equals(taskType) ? "patrol" : "realtime");
        float conf = task.getDetectConf() != null ? task.getDetectConf() : 0.5f;
        int cooldown = task.getAlertEventSuppressTime() != null ? task.getAlertEventSuppressTime() : 30;
        String algoName = task.getModelNames() != null && !task.getModelNames().isBlank()
                ? task.getModelNames().split(",")[0].trim()
                : "detection";
        int frameSkip = task.getExtractInterval() != null && task.getExtractInterval() > 0
                ? task.getExtractInterval()
                : 12;
        boolean preferGpu = task.getPreferGpu() == null || task.getPreferGpu();
        boolean alertEnabled = Boolean.TRUE.equals(task.getAlertEventEnabled());

        String content = """
                # Auto-generated by video-server-java for executor=cpp
                [video]
                rtsp_url=%s
                rtmp_url=
                width=1920
                height=1080
                fps=25

                [ai]
                enable=true
                model_path=%s
                classes_path=%s
                threads=2
                frame_skip=%d
                prefer_gpu=%s
                force_cpu=%s
                gpu_device_id=0

                [alarm]
                enable=%s
                hook_url=%s
                confidence_threshold=%s
                cooldown_time=%d
                image_dir=%s

                [task]
                id=%d
                control_port=%d

                [video_task]
                device_id=%s
                device_name=%s
                task_type=%s
                algorithm_name=%s
                alert_hook_url=%s
                heartbeat_url=%s
                heartbeat_interval_sec=%s
                log_path=%s
                alert_image_dir=%s
                headless=true
                frame_skip=%d

                [features]
                enable_rtmp=false
                enable_draw=true
                enable_alarm=%s
                """.formatted(
                rtspUrl,
                modelPath,
                classesPath,
                frameSkip,
                preferGpu ? "true" : "false",
                preferGpu ? "false" : "true",
                alertEnabled ? "true" : "false",
                hookUrl,
                conf,
                cooldown,
                alertImageDir.toString().replace('\\', '/'),
                task.getId(),
                controlPort,
                device.get("id"),
                device.get("name"),
                taskType,
                algoName,
                hookUrl,
                heartbeatUrl,
                "patrol".equals(taskType) ? "15" : "10",
                logPath.toString().replace('\\', '/'),
                alertImageDir.toString().replace('\\', '/'),
                frameSkip,
                alertEnabled ? "true" : "false"
        );
        Files.writeString(iniPath, content);
        return iniPath.toString();
    }

    public String resolveRuntimeBin(AlgorithmTaskRow task) {
        if (task.getRuntimeBinPath() != null && !task.getRuntimeBinPath().isBlank()) {
            Path custom = Path.of(task.getRuntimeBinPath());
            if (Files.isRegularFile(custom)) {
                return custom.toString();
            }
        }
        String env = System.getenv("RUNTIME_BIN");
        if (env != null && !env.isBlank() && Files.isRegularFile(Path.of(env))) {
            return env;
        }
        Path root = repoRoot();
        List<Path> candidates = List.of(
                root.resolve("RUNTIME/build-win/Release/RUNTIME.exe"),
                root.resolve("RUNTIME/build/Release/RUNTIME.exe"),
                root.resolve("RUNTIME/build/RUNTIME")
        );
        for (Path p : candidates) {
            if (Files.isRegularFile(p)) {
                return p.toString();
            }
        }
        throw new VideoBusinessException(400,
                "RUNTIME 二进制不存在。请先编译 RUNTIME 或设置 RUNTIME_BIN / task.runtime_bin_path");
    }

    private String resolveModelPath() {
        Path root = repoRoot();
        Path p = root.resolve("RUNTIME/models/yolov11n.onnx");
        if (Files.isRegularFile(p)) {
            return p.toString().replace('\\', '/');
        }
        String env = System.getenv("RUNTIME_MODEL_PATH");
        if (env != null && !env.isBlank()) {
            return env.replace('\\', '/');
        }
        return p.toString().replace('\\', '/');
    }

    private String resolveClassesPath() {
        Path root = repoRoot();
        Path p = root.resolve("RUNTIME/models/coco.names");
        if (Files.isRegularFile(p)) {
            return p.toString().replace('\\', '/');
        }
        return p.toString().replace('\\', '/');
    }

    private Path repoRoot() {
        Path videoRoot = Path.of(System.getProperty("user.dir"));
        if (Files.isDirectory(videoRoot.resolve("RUNTIME"))) {
            return videoRoot;
        }
        Path sibling = videoRoot.getParent() != null ? videoRoot.getParent().resolve("RUNTIME") : null;
        if (sibling != null && Files.isDirectory(sibling)) {
            return sibling.getParent();
        }
        return Path.of("F:/acme");
    }

    private String normalizeTaskType(String taskType) {
        String tt = taskType != null ? taskType.trim().toLowerCase() : "realtime";
        if ("snapshot".equals(tt)) {
            return "snap";
        }
        return tt;
    }
}
