debug: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15432/iot-video20?autoReconnect=true&useUnicode=true&characterEncoding=utf8&stringtype=unspecified
    username: postgres
    password: iot45722414822

management:
  health:
    db:
      enabled: false

video:
  alert:
    use-direct-persist: true
  runtime:
    repo-root: F:/acme
