debug: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15432/iot-video20?autoReconnect=true&useUnicode=true&characterEncoding=utf8&stringtype=unspecified
    username: postgres
    password: iot45722414822

video:
  alert:
    use-direct-persist: true
    alert-notification-topic: iot-alert-notification
    snapshot-alert-topic: iot-snapshot-alert
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  matching:
    use-direct-process: true
    face-matching-topic: iot-face-matching
    plate-matching-topic: iot-plate-matching
  inference:
    enabled: true
    timeout-seconds: 120
  post-process:
    use-stub-enqueue: true
    workspace-root: ${user.home}/.video-java/post-process-workspaces
    sink-host: 127.0.0.1
    sink-port: "48092"
    sink-use-gateway: false
    gateway-url: http://localhost:48080
    enqueue-timeout-ms: 5000
  node-remote:
    remote-deploy-enabled: false
    gateway-url: http://localhost:48099
